.gitignore
ansible/roles/prosody/files/mod_websocket_session_ip-0.12.patch
ansible/roles/prosody/tasks/install.yml

- Ignore .swp files.
- fix: Apply mod_websocket_session_ip for prosody 0.12.

fix: Apply mod_websocket_session_ip for prosody 0.12.

---

ansible/roles/prosody/files/mod_rate_limit.lua

**This PR is not tested in any way!** It was just the easiest way to share suggested code changes :)
---
Commit message follows:
The session ip field, especially before the connection is fully initialized (e.g. at the point that filter hooks get called) is not always accurate. For example, it may be set to the network IP that the connection came from, rather than the IP of the remote client (which may be determined by HTTP headers).
Prosody 0.12.3 will [provide an API](https://hg.prosody.im/0.12/rev/3a6dae39c70e) to access the request object, allowing access to the client's IP. For older versions, I've included the snippet of code in that helper function directly in this module. As it uses internal "private" implementation details, it should be removed if/when compatibility with older …

mod_rate_limit: pull real client IP from request

---

ansible/roles/haproxy-tenant-pin/defaults/main.yml
ansible/roles/haproxy-tenant-pin/files/haproxy_tenant_sync.py
ansible/roles/hcv-haproxy-configure/defaults/main.yml
ansible/roles/hcv-haproxy-configure/tasks/main.yml
ansible/roles/hcv-haproxy-configure/templates/haproxy.cfg.j2

Tested on haproxy in jitsi-net, works as expected

feature: ban rooms from consul values

---

.gitmodules
ansible/configure-jvb-local-oracle.yml
ansible/configure-standalone.yml
ansible/roles/consul-standalone/defaults/main.yml
ansible/roles/consul-standalone/templates/standalone.json.j2
ansible/roles/jitsi-videobridge/files/shards.json.template
ansible/roles/jitsi-videobridge/files/xmpp.conf.template
ansible/roles/jitsi-videobridge/tasks/configure.yml
ansible/roles/jitsi-videobridge/tasks/install.yml
ansible/roles/jitsi-videobridge/templates/consul-template.env.j2
ansible/roles/jitsi-videobridge/templates/jvb.conf.j2
ansible/roles/jitsi-videobridge/templates/xmpp.conf.j2
scripts/configure-standalone-oracle.sh

support consul-template for JVB

feature: split JVB xmpp conf to separate file

---

ansible/roles/prosody/templates/prosody.cfg.lua.j2

To ignore propagating jibri and transcribers to visitor nodes.

fix: Enables ignore list for visitors.

---

ansible/roles/jitsi-meet/defaults/main.yml
ansible/roles/jitsi-meet/templates/config.js.j2

- Move stereo under audioQuality.
- Order keys alphabetically.
- Add a flag for DTX.

Add a flag for DTX

---

ansible/roles/nodejs/defaults/main.yml

Reverts jitsi/infra-configuration#166

Revert "Upgrade nodejs to v 16.16.0"

---

ansible/roles/hcv-haproxy-configure/templates/haproxy.cfg.j2
ansible/roles/hcv-haproxy-configure/templates/haproxy.cfg.template.j2

hat tip to @bgrozev for figuring this one out!

fix: haproxy is sticking on 'if'

---

ansible/build-java-jibri-oracle.yml
ansible/configure-jibri-java-local-oracle.yml
ansible/roles/jitsi-upload-integrations/defaults/main.yml
ansible/roles/jitsi-upload-integrations/tasks/main.yml

Reverts jitsi/infra-configuration#176

Revert "Cleanup jitsi-upload-integrations role"

---

ansible/roles/selenium-grid/handlers/main.yml

Drop docker and its interface before restarting the hub and node.

fix: Fixes selenium ip discovery.

---

ansible/roles/jitsi-videobridge/files/jvb-health-check-oracle.sh

extended health check was working as expected

Revert "task: disable JVB extended health checks (#270)"

---

ansible/roles/jitsi-meet/templates/config.js.j2
ansible/roles/prosody/files/mod_muc_password_preset.lua
ansible/roles/prosody/templates/prosody.cfg.lua.j2

Adds separate property for persistent lobby and adds additional config.js values to accommodate sso pages.

feat: Adds option to specify more custom token auth url.

---

ansible/roles/prosody/files/mod_muc_password_preset.lua

from the conference mapper, and set them in the MUC config form.

feat: Read visitorsEnabled and participantsSoftLimit

---

ansible/roles/prosody/templates/prosody.cfg.lua.j2

Just to match closer to the config we have in docker-jitsi-meet
https://github.com/jitsi/docker-jitsi-meet/pull/1728

Move "ping" to global modules_enabled

---

ansible/roles/prosody/templates/prosody.cfg.lua.j2

- Fix loading modules when rate limit disabled.
- fix: Set muc_max_occupants for lobby and breakout rooms.

Set muc_max_occupants for lobby and breakout rooms.

---

ansible/roles/jitsi-meet/defaults/main.yml

fix: recordings defaults

---

ansible/roles/prosody/files/mod_muc_webhooks.lua

the participant id is the first part until dash from the bare jid. This applies for joined,left and sip in/out, for dial in/out the participantId is different ( probably from other jid?)

feat: add participant id on webhooks payload

---

ansible/roles/prosody/files/mod_muc_events.lua

We were filtering the end conference which was preventing sending chat uploaded event for jaas rooms.

fix: Filtering for jaas rooms.

---

ansible/roles/jitsi-meet/defaults/main.yml
ansible/roles/jitsi-meet/files/sanitize.js
ansible/roles/jitsi-meet/templates/config.js.j2
ansible/roles/jitsi-videobridge/tasks/configure.yml

- Remove jvb callstats task (commented out).
- Remove remaining callstats options.

Remove remaining callstats options

---

ansible/roles/prosody/files/mod_muc_webhooks.lua

Some of the logs were even doing inspect on big object to be replaced into a string and dumped on every join/leave and even worse on every transcription chunk.

feat(webhooks): Put debug logs behind a flag.

---

ansible/roles/jigasi-auth/defaults/main.yml
ansible/roles/jigasi/defaults/main.yml
ansible/roles/jigasi/templates/environments.json.j2
ansible/roles/jigasi/templates/sip-communicator.properties.j2

- **Add option to use A/B accounts for the jigasi conference login.**
- **Add option to use A/B account for transcriber conference login.**
- **Add option to use A/B accounts for jigasi brewery.**

Add option to use A/B accounts for jigasi

---

ansible/roles/prosody/templates/prosody.cfg.lua.j2
ansible/roles/prosody/templates/prosody.cfg.lua.visitor.j2

Update smacks_max_old_sessions.
We need smacks_max_old_sessions if we are going to use the same username for different connections ...

feat: Adds jigasi hosts to visitors.

---

ansible/roles/jitsi-videobridge/defaults/main.yml
ansible/roles/jitsi-videobridge/templates/jvb.conf.j2

- **ref(jvb): Remove old multi-stream option.**
- **feat(jvb): Enable CPU stress by default.**

feat(jvb): Enable CPU stress by default.

---

ansible/roles/jitsi-videobridge/defaults/main.yml
ansible/roles/jitsi-videobridge/tasks/install.yml
ansible/roles/jitsi-videobridge/templates/config.j2

It gets outdated very quickly when YK release a new version, so isn't
useful in practice.

ref(jvb): Remove yourkit agent automation.

---

ansible/roles/prosody/files/mod_muc_auth_vpaas.lua
ansible/roles/prosody/files/mod_muc_permissions_vpaas.lua
ansible/roles/prosody/files/mod_muc_webhooks.lua

The use case is 8x8 users clicking jaas links in work apps and using a valid 8x8 token.

feat(auth_vpaas): Allows those using valid token to join as guests.

---

ansible/roles/prosody/files/mod_muc_events.lua
ansible/roles/prosody/files/mod_muc_password_preset.lua
ansible/roles/prosody/files/mod_muc_permissions_vpaas.lua
ansible/roles/prosody/files/util.internal.lib.lua

Performance improvement as we were reading the key file on every room creation.

feat: Clear generateToken duplicate code.

---

ansible/roles/jitsi-videobridge/files/list-large-conferences.sh
ansible/roles/jitsi-videobridge/tasks/configure.yml

meet.jit.si/a	meet-jit-si-us-ashburn-1-s4	20
meet.jit.si/b	meet-jit-si-us-ashburn-1-s4	17
meet.jit.si/c	meet-jit-si-ap-sydney-1-s3	16

feat(jvb): Add a script to list the largest conferences on a bridge

---

ansible/roles/prosody/files/mod_muc_events.lua

When backend recording with transcriptions is enabled only then we need to send the transcriptions to the service.

fix(recording): Send transcriptions only when recording is on.

---

ansible/roles/jicofo/defaults/main.yml
ansible/roles/jicofo/templates/jicofo.conf.j2
ansible/roles/prosody/templates/prosody.cfg.lua.j2
ansible/roles/prosody/templates/prosody.cfg.lua.visitor.j2

- feat(jicofo): Option to disable moderator checks.
- fix(prosody): Drops not available module.
- feat(visitors): Allows transcriber as main participant.
- feat(visitors): Allows visitors to invite jigasi in main meeting.

jwt and jigasi visitors

---

ansible/roles/jigasi/defaults/main.yml

remove transcriber-specific list of datacenters

chore(jigasi-transcriber): remove mumbai transcriber region

---

ansible/roles/prosody/files/mod_muc_webhooks.lua

When occupant leaves most of the data is already cleared from presence. Keep cache with display name changes and use that. Keep the cache attached to the room, so when room is cleaned same will happen with the cache.

fix(webhooks): Fixes display name for leave events.

---

ansible/roles/prosody/files/mod_muc_webhooks.lua

When stanza is missing make sure we use the cache.

fix(webhooks): Fixes display name for kick events.

---

ansible/roles/jitsi-meet/defaults/main.yml
ansible/roles/jitsi-meet/templates/config.js.j2

Add config flag that enables showing the recording consent dialog on the spot tv.

feat: add spot consent flag
